config/routes.rb
 Rails.application.routes.draw do
 
	resources :contact
	resources :gossips 
	resources :users
	resources :city
	resources :team


end
 


 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
		# has_many :users
		# has_many :gossips
	  validates :name, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	# belongs_to :city
	validates :title, presence: true
	validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
   def index
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
      @gossips = Gossip.all 
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
     @gossip = Gossip.find(params[:id].to_i)
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
      @gossip = Gossip.new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create

    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit

      @gossip = Gossip.find(params[:id].to_i)
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
      @gossip = Gossip.find(params[:id].to_i)
      if @gossip.update(title: params[:title], content: params[:content])
        redirect_to gossips_path
      else
        render :edit
      end
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<body style="background-color:#FFDD51;">

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Contactez-nous !</h1>
<p>Comment nous contacter ? </p>

  </div>
</div>
<body>

app/views/gossips/edit.html.erb
 v
<!------_________GOSSIP EDIT FORM_______---->

 <div class="card" style="width: 18rem;">


  <div class="container">
  <h1> Éditer le potin</h1>

<%= link_to 'Revenir au potin', gossip_path %>

        <%= form_for :gossip, url: gossip_path do |f| %>
          <p>
             <h5 class="card-title"> <%= f.label :Titre %><br> </h5>
            <%= f.text_field :title %>
          </p>

          <p>
            <%= f.label :Contenu %><br>
            <%= f.text_area :content %>
          </p>

         <%= link_to "Edit your gossip", gossip_path, class: "btn btn-warning", method: :patch %>
        <% end %>


</div>

app/views/gossips/index.html.erb
 
<!-- _______________END NAVBAR___________________________-->
<!-- create with boostrap code-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand" href="#">The Gossip Project</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        
        <li class="nav-item active">
        <a class="http://localhost:3000/team" href="http://localhost:3000/team">Team <span class="sr-only">(current)</span></a>
        </li>

              <li class="nav-item">
              <a class= "lala"> <a class="t" href="http://localhost:3000/contact">Contact</a> 
              </li>
              <li class="nav-item"></li>
      </ul>
    </div>

</nav>


<!-- _______________TEXT + IMAGE___________________________-->

    <div class="card">

<body style="background-color:#FFDD51;">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">

    <div class="img">
    <a href="http://zupimages.net/viewer.php?id=19/44/u28y.jpg"><img src="https://zupimages.net/up/19/44/u28y.jpg" alt="" /></a>
    </div>

  </div>
    <div class="card">
<center>
    <h2> Hello <%= @first_name %> ! Tu as un gossip à partager ? 

      <div><a href="<%= new_gossip_path %> "class="btn btn-success"> Créer un gossip </a >  </h2> </div>
</center>
    <div> 
      <center>
    <h3>Les derniers gossips créés... </h3>
    </center>
    <div>

    </div>
    </div>


<!-- _______________GOSSIP INDEX - GENERATE WITH FAKER___________________________-->



    <div class="container">
    <div class="row">
    <%Gossip.all.each do |gossip|%>
    <div class="card-deck col-xs-12 col-sm-12 col-md-4 col-lg-4">
    <div class="card">
    <div class="card-header"> Gossip #<%=gossip.id%> </div>
    <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
    <p><%=gossip.title%></p>
    </blockquote>
    </div>
    <footer class="blockquote-footer">
    <div class="row justify-content-between align-self-center mx-3">
    <a class="btn btn-warning" <%= link_to "Voir le gossip", gossip_path(gossip.id)%>
    </a>
    </div>
    </footer>
    </div> 
    </div>
    <%end%>
    </div>
  </div>
​</body>

app/views/gossips/new.html.erb
<div class="card" style="width: 48rem;">


  <div class="container">
  <h1> Créer un gossip</h1>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
  <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
  <br />
  <div class="row justify-content-center align-self-center mx-5">
  <div class="col-3">
  <%= label_tag 'Titre' %>
  </div>
  <div class="col-3">
  <%= text_field_tag 'gossip_title', value = nil, options = {style:"height:30px;width:300px"} %>
  </div>
  </div>     
  <br />
  <div class="row justify-content-center align-self-center mx-5">
  <div class="col-3">
  <%= label_tag 'Potin' %>
  </div>
  <div class="col-3">
  <%= text_field_tag 'gossip_content', value = nil, options = {style:"height:120px;width:300px;vertical-align:text-top"}%>
  </div>
  </div>

  <a href="<%= gossips_path %> " class= "btn btn-warning"> Valider</a>

  <% end %>
  </div>
  </body>
  </div>
  </div>

</div>

app/views/gossips/show.html.erb
 <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @gossip.title %> </h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @gossip.id %></h6>
    <p class="card-text"> <%= @gossip.content %> </p>
    <p class="card-text"> <%= @user%> </p>



    <a href="<%= edit_gossip_path %>" class="card-link">Modifier</a>
    <a href="#" class="card-link">Supprimer</a>

  </div>
</div>

 
<div class="card" style="width: 18rem;">

<a href="<%= gossips_path %> " class= "btn btn-warning"> Revenir à la page d'accueil avec tous les potins</a>

 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>The Gossip Project </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
<nav class="navbar navbar-expand-lg navbar-light text-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand text-white" <%= link_to "The Gossip Project", gossips_path%>></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
     
      <li class="nav-item">
       
      </li>
    </ul>
  </div>
</nav>
  </header>
  <body>
    
    <%= yield %>
  </body>
</html>

app/views/team/index.html.erb
<div style="background-color:#FFDD51;">

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Notre team</h1>
    <p class="lead">Voici la team</p>
  </div>
</div>

<footer>

<ul class="list-group list-group-flush">
  <li class="list-group-item">James</li>
  <li class="list-group-item">Yoni</li>
  <li class="list-group-item">Zoran</li>
  <li class="list-group-item">Julien</li>
  <li class="list-group-item">Ombeline</li>
</ul>
</footer>
			</ul>
		</div>
	</div>
</div>

app/views/user/show.html.erb
<div class="card">
  <div class="card-header font-weight-bold">
    Author #<%=params[:id]%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= User.find(params[:id]).first_name%> <%= User.find(params[:id]).last_name%></h5>
    <div class="card-text">
    	<p>email address : <%= User.find(params[:id]).email%></p>
    	<p>Age : <%= User.find(params[:id]).age%></p>
		<p>City : <%= User.find(params[:id]).city.name%></p>
		<p>ZIP Code : <%= User.find(params[:id]).city.zip_code%></p>
		<p>Membre depuis le : <%= User.find(params[:id]).created_at.to_date%></p>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header mb-3">
    <% if Gossip.where(user_id:params[:id]).size == 0 %>
    <p><%= User.find(params[:id]).first_name%> n'a pas encore écrit de gossip</p>
    <% else %>
    <p><%= User.find(params[:id]).first_name%> a écrit le(s) <%=Gossip.where(user_id:params[:id]).size%> gossip(s) suivant(s) :</p>
    <%end%>
   </div>
<div class="card-deck">
<%Gossip.where(user_id:params[:id]).each do |gossip|%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header">
    Gossip #<%=gossip.id%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=gossip.title%></p>
      <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
      	<p><%=User.find(gossip.user_id).first_name%> <%=User.find(gossip.user_id).last_name%></p>
      	<a class="btn btn-dark" <%= link_to "Voir", gossip_path(gossip.id)%></a>
      </div>
      </footer>
    </blockquote>
  </div>
</div>
</div>
<%end%>c
</div>
</div>